[package]
name = "r_pso"
version = "0.1.0"
authors = ["magpaccio <73834898+magpaccio@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
